DROP TABLE MEAL_RECORD;
DROP TABLE MEAL;
DROP TABLE FOOD;
DROP TABLE EX_RECORD;
DROP TABLE EX_PERFORMANCE;
DROP TABLE EXERCISE;
DROP TABLE BODYPART;
DROP TABLE REPLY;
DROP TABLE BOARD;
DROP TABLE CATEGORY;
DROP TABLE USER_PIC;
DROP TABLE MEMBER;

--==============================================================================
-- 회원 테이블
CREATE TABLE MEMBER (
	USER_NO number PRIMARY KEY,
	USER_NAME varchar2(15) NOT NULL,
	USER_NICKNAME varchar2(30) NOT NULL,
	USER_EMAIL varchar2(100) NOT NULL,
	USER_PWD varchar2(100)	NOT NULL,
	GENDER	varchar2(1)	NOT NULL CHECK (GENDER IN ('M','F')),
	AGE number NOT NULL,
	HEIGHT	number NULL,
	WEIGHT	number	NULL,
	SMM	number		NULL,
	BFP	number		NULL,
	USER_POINT	number	DEFAULT 0,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.USER_NICKNAME IS '회원닉네임';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '회원이메일';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.GENDER IS '성별(M/F)';
COMMENT ON COLUMN MEMBER.AGE IS '나이';
COMMENT ON COLUMN MEMBER.HEIGHT IS '키';
COMMENT ON COLUMN MEMBER.WEIGHT IS '몸무게';
COMMENT ON COLUMN MEMBER.SMM IS '골격근량';
COMMENT ON COLUMN MEMBER.BFP IS '체지방률';
COMMENT ON COLUMN MEMBER.USER_POINT IS '회원점수';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';
COMMENT ON COLUMN MEMBER.STATUS IS '회원상태(Y/N)';

CREATE SEQUENCE SEQ_UNO
NOCACHE;

INSERT INTO MEMBER
VALUES (SEQ_UNO.NEXTVAL, '관리자', 'admin', 'admin@ps5.com', 'qwer', 'M', 22, NULL, NULL, NULL, NULL, 0,sysdate,sysdate,'Y');
--==============================================================================
--회원 프로필 사진 테이블
CREATE TABLE USER_PIC (
    PIC_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    ORIGIN_NAME VARCHAR2(255) NOT NULL,
    CHANGE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH VARCHAR2(1000) NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN USER_PIC.PIC_NO IS '회원프로필사진번호';
COMMENT ON COLUMN USER_PIC.USER_NO IS '회원번호';
COMMENT ON COLUMN USER_PIC.ORIGIN_NAME IS '사진파일원본명';
COMMENT ON COLUMN USER_PIC.CHANGE_NAME IS '사진파일수정명';
COMMENT ON COLUMN USER_PIC.FILE_PATH IS '사진파일경로';


--==============================================================================
-- 카테고리 테이블
CREATE TABLE CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '카테고리명';

INSERT INTO CATEGORY VALUES(10, '자유');
INSERT INTO CATEGORY VALUES(20, '헬창');
INSERT INTO CATEGORY VALUES(30, '헬린이');
INSERT INTO CATEGORY VALUES(40, 'QnA');

--==============================================================================
-- 게시판 테이블
CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    CATEGORY_NO NUMBER,
    BOARD_TITLE VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    BOARD_WRITER NUMBER NOT NULL,
    COUNT NUMBER DEFAULT 0,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO)
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자회원번호';
COMMENT ON COLUMN BOARD.COUNT IS '조회수';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일';
COMMENT ON COLUMN BOARD.STATUS IS '상태값(Y/N)';

CREATE SEQUENCE SEQ_BNO
NOCACHE;
--==============================================================================
-- 댓글 테이블
CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(400) NOT NULL,
    REF_BNO NUMBER NOT NULL,
    REPLY_WRITER NUMBER NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y','N')),
    FOREIGN KEY (REF_BNO) REFERENCES BOARD(BOARD_NO),
    FOREIGN KEY (REPLY_WRITER) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.REF_BNO IS '참조하는게시글번호';
COMMENT ON COLUMN REPLY.REPLY_WRITER IS '작성자회원번호';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '작성일';
COMMENT ON COLUMN REPLY.STATUS IS '상태값(Y/N)';

CREATE SEQUENCE SEQ_RNO
NOCACHE;
--==============================================================================
-- 운동부위 테이블
CREATE TABLE BODYPART (
    BPART_NO NUMBER PRIMARY KEY,
    BPART_NAME VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN BODYPART.BPART_NO IS '운동부위번호';
COMMENT ON COLUMN BODYPART.BPART_NAME IS '운동부위';

INSERT INTO BODYPART VALUES (1,'등');
INSERT INTO BODYPART VALUES (2,'어깨');
INSERT INTO BODYPART VALUES (3,'가슴');
INSERT INTO BODYPART VALUES (4,'다리');
INSERT INTO BODYPART VALUES (5,'팔');

--==============================================================================
--운동이름
CREATE TABLE EXERCISE (
    EX_NO NUMBER PRIMARY KEY,
    BPART_NO NUMBER NOT NULL,
    EX_NAME VARCHAR2(50) NOT NULL,
    FOREIGN KEY (BPART_NO) REFERENCES BODYPART(BPART_NO)
);

COMMENT ON COLUMN EXERCISE.EX_NO IS '운동번호';
COMMENT ON COLUMN EXERCISE.BPART_NO IS '운동부위번호';
COMMENT ON COLUMN EXERCISE.EX_NAME IS '운동이름';

--==============================================================================
--운동수행 테이블
CREATE TABLE EX_PERFORMANCE (
    EXP_NO NUMBER PRIMARY KEY,
    EX_NO NUMBER NOT NULL,
    BPART_NO NUMBER NOT NULL,
    EXP_SET NUMBER NOT NULL,
    EXP_WEIGHT NUMBER NOT NULL,
    EXP_COUNT NUMBER NOT NULL,
    FOREIGN KEY (EX_NO) REFERENCES EXERCISE(EX_NO),
    FOREIGN KEY (BPART_NO) REFERENCES BODYPART(BPART_NO)
);

COMMENT ON COLUMN EX_PERFORMANCE.EXP_NO IS '운동수행번호';
COMMENT ON COLUMN EX_PERFORMANCE.EX_NO IS '운동번호';
COMMENT ON COLUMN EX_PERFORMANCE.BPART_NO IS '운동부위번호';
COMMENT ON COLUMN EX_PERFORMANCE.EXP_SET IS '운동수행세트수';
COMMENT ON COLUMN EX_PERFORMANCE.EXP_WEIGHT IS '운동수행중량';
COMMENT ON COLUMN EX_PERFORMANCE.EXP_COUNT IS '운동수행횟수';

CREATE SEQUENCE SEQ_EXPN
NOCACHE;
--==============================================================================
--운동기록
CREATE TABLE EX_RECORD(
    EXR_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    EXP_NO NUMBER NOT NULL,
    EXR_RECORD_DATE DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (EXP_NO) REFERENCES EX_PERFORMANCE(EXP_NO)
);

COMMENT ON COLUMN EX_RECORD.EXR_NO IS '운동기록번호';
COMMENT ON COLUMN EX_RECORD.USER_NO IS '회원번호';
COMMENT ON COLUMN EX_RECORD.EXP_NO IS '운동수행번호';
COMMENT ON COLUMN EX_RECORD.EXR_RECORD_DATE IS '운동기록날짜';

CREATE SEQUENCE SEQ_EXRN
NOCACHE;
--==============================================================================
-- 음식 테이블
CREATE TABLE FOOD (
    FOOD_NO NUMBER PRIMARY KEY,
    FOOD_NAME VARCHAR2(50) NOT NULL,
    FOOD_KCAL number NOT NULL,
    CARB number NOT NULL,
    PROTEIN number NOT NULL,
    FAT number NOT NULL
);

COMMENT ON COLUMN FOOD.FOOD_NO IS '음식번호';
COMMENT ON COLUMN FOOD.FOOD_NAME IS '음식이름';
COMMENT ON COLUMN FOOD.FOOD_KCAL IS '음식칼로리';
COMMENT ON COLUMN FOOD.CARB IS '탄수화물';
COMMENT ON COLUMN FOOD.PROTEIN IS '단백질';
COMMENT ON COLUMN FOOD.FAT IS '지방';

--==============================================================================
-- 식사 테이블
CREATE TABLE MEAL (
    MEAL_NO NUMBER PRIMARY KEY,
    FOOD_NO NUMBER NOT NULL,
    FOOD_AMOUNT NUMBER NOT NULL,
    WHEN_EAT VARCHAR(1) NOT NULL CHECK (WHEN_EAT IN ('B','L','D','E')),
    FOREIGN KEY (FOOD_NO) REFERENCES FOOD(FOOD_NO)
);

COMMENT ON COLUMN MEAL.MEAL_NO IS '식사번호';
COMMENT ON COLUMN MEAL.FOOD_NO IS '음식번호';
COMMENT ON COLUMN MEAL.FOOD_AMOUNT IS '음식개수';
COMMENT ON COLUMN MEAL.WHEN_EAT IS '식사타이밍(B:아침, L:점심, D:저녁, E:간식/기타)';

CREATE SEQUENCE SEQ_MN
NOCACHE;
--==============================================================================
-- 식사기록테이블
CREATE TABLE MEAL_RECORD (
    MR_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    MEAL_NO NUMBER NOT NULL,
    WHEN_EAT_DATE DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (MEAL_NO) REFERENCES MEAL(MEAL_NO)
);

COMMENT ON COLUMN MEAL_RECORD.MR_NO IS '식사기록번호';
COMMENT ON COLUMN MEAL_RECORD.USER_NO IS '유저번호';
COMMENT ON COLUMN MEAL_RECORD.MEAL_NO IS '식사번호';
COMMENT ON COLUMN MEAL_RECORD.WHEN_EAT_DATE IS '식사날짜';

CREATE SEQUENCE SEQ_MRN
NOCACHE;
--======생성 후 커밋=============================================================
COMMIT;