-- 1 에서  107  행에 대한 삽입 실패
--ORA-01722: invalid number
--행 1
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목1','내용1',1,0,to_date('2024-01-02', 'RRRR-MM-DD'),'Y');
--행 2
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목2','내용2',2,0,to_date('2024-01-03', 'RRRR-MM-DD'),'Y');
--행 3
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목3','내용3',1,0,to_date('2024-01-04', 'RRRR-MM-DD'),'Y');
--행 4
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목4','내용4',2,0,to_date('2024-01-05', 'RRRR-MM-DD'),'Y');
--행 5
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목5','내용5',1,0,to_date('2024-01-06', 'RRRR-MM-DD'),'Y');
--행 6
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목6','내용6',2,0,to_date('2024-01-07', 'RRRR-MM-DD'),'Y');
--행 7
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목7','내용7',1,0,to_date('2024-01-08', 'RRRR-MM-DD'),'Y');
--행 8
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목8','내용8',2,0,to_date('2024-01-09', 'RRRR-MM-DD'),'Y');
--행 9
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목9','내용9',1,0,to_date('2024-01-10', 'RRRR-MM-DD'),'Y');
--행 10
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목10','내용10',2,0,to_date('2024-01-11', 'RRRR-MM-DD'),'Y');
--행 11
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목11','내용11',1,0,to_date('2024-01-12', 'RRRR-MM-DD'),'Y');
--행 12
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목12','내용12',2,0,to_date('2024-01-13', 'RRRR-MM-DD'),'Y');
--행 13
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목13','내용13',1,0,to_date('2024-01-14', 'RRRR-MM-DD'),'Y');
--행 14
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목14','내용14',2,0,to_date('2024-01-15', 'RRRR-MM-DD'),'Y');
--행 15
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목15','내용15',1,0,to_date('2024-01-16', 'RRRR-MM-DD'),'Y');
--행 16
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목16','내용16',2,0,to_date('2024-01-17', 'RRRR-MM-DD'),'Y');
--행 17
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목17','내용17',1,0,to_date('2024-01-18', 'RRRR-MM-DD'),'Y');
--행 18
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목18','내용18',2,0,to_date('2024-01-19', 'RRRR-MM-DD'),'Y');
--행 19
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목19','내용19',1,0,to_date('2024-01-20', 'RRRR-MM-DD'),'Y');
--행 20
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목20','내용20',2,0,to_date('2024-01-21', 'RRRR-MM-DD'),'Y');
--행 21
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목21','내용21',1,0,to_date('2024-01-22', 'RRRR-MM-DD'),'Y');
--행 22
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목22','내용22',2,0,to_date('2024-01-23', 'RRRR-MM-DD'),'Y');
--행 23
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목23','내용23',1,0,to_date('2024-01-24', 'RRRR-MM-DD'),'Y');
--행 24
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목24','내용24',2,0,to_date('2024-01-25', 'RRRR-MM-DD'),'Y');
--행 25
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목25','내용25',1,0,to_date('2024-01-26', 'RRRR-MM-DD'),'Y');
--행 26
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목26','내용26',2,0,to_date('2024-01-27', 'RRRR-MM-DD'),'Y');
--행 27
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목27','내용27',1,0,to_date('2024-01-28', 'RRRR-MM-DD'),'Y');
--행 28
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목28','내용28',2,0,to_date('2024-01-29', 'RRRR-MM-DD'),'Y');
--행 29
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목29','내용29',1,0,to_date('2024-01-30', 'RRRR-MM-DD'),'Y');
--행 30
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목30','내용30',2,0,to_date('2024-01-31', 'RRRR-MM-DD'),'Y');
--행 31
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목31','내용31',1,0,to_date('2024-02-01', 'RRRR-MM-DD'),'Y');
--행 32
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목32','내용32',2,0,to_date('2024-02-02', 'RRRR-MM-DD'),'Y');
--행 33
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목33','내용33',1,0,to_date('2024-02-03', 'RRRR-MM-DD'),'Y');
--행 34
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목34','내용34',2,0,to_date('2024-02-04', 'RRRR-MM-DD'),'Y');
--행 35
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목35','내용35',1,0,to_date('2024-02-05', 'RRRR-MM-DD'),'Y');
--행 36
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목36','내용36',2,0,to_date('2024-02-06', 'RRRR-MM-DD'),'Y');
--행 37
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목37','내용37',1,0,to_date('2024-02-07', 'RRRR-MM-DD'),'Y');
--행 38
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목38','내용38',2,0,to_date('2024-02-08', 'RRRR-MM-DD'),'Y');
--행 39
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목39','내용39',1,0,to_date('2024-02-09', 'RRRR-MM-DD'),'Y');
--행 40
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목40','내용40',2,0,to_date('2024-02-10', 'RRRR-MM-DD'),'Y');
--행 41
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목41','내용41',1,0,to_date('2024-02-11', 'RRRR-MM-DD'),'Y');
--행 42
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목42','내용42',2,0,to_date('2024-02-12', 'RRRR-MM-DD'),'Y');
--행 43
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목43','내용43',1,0,to_date('2024-02-13', 'RRRR-MM-DD'),'Y');
--행 44
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목44','내용44',2,0,to_date('2024-02-14', 'RRRR-MM-DD'),'Y');
--행 45
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목45','내용45',1,0,to_date('2024-02-15', 'RRRR-MM-DD'),'Y');
--행 46
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목46','내용46',2,0,to_date('2024-02-16', 'RRRR-MM-DD'),'Y');
--행 47
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목47','내용47',1,0,to_date('2024-02-17', 'RRRR-MM-DD'),'Y');
--행 48
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목48','내용48',2,0,to_date('2024-02-18', 'RRRR-MM-DD'),'Y');
--행 49
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목49','내용49',1,0,to_date('2024-02-19', 'RRRR-MM-DD'),'Y');
--행 50
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목50','내용50',2,0,to_date('2024-02-20', 'RRRR-MM-DD'),'Y');
--행 51
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목51','내용51',1,0,to_date('2024-02-21', 'RRRR-MM-DD'),'Y');
--행 52
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목52','내용52',2,0,to_date('2024-02-22', 'RRRR-MM-DD'),'Y');
--행 53
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목53','내용53',1,0,to_date('2024-02-23', 'RRRR-MM-DD'),'Y');
--행 54
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목54','내용54',2,0,to_date('2024-02-24', 'RRRR-MM-DD'),'Y');
--행 55
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목55','내용55',1,0,to_date('2024-02-25', 'RRRR-MM-DD'),'Y');
--행 56
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목56','내용56',2,0,to_date('2024-02-26', 'RRRR-MM-DD'),'Y');
--행 57
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목57','내용57',1,0,to_date('2024-02-27', 'RRRR-MM-DD'),'Y');
--행 58
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목58','내용58',2,0,to_date('2024-02-28', 'RRRR-MM-DD'),'Y');
--행 59
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목59','내용59',1,0,to_date('2024-02-29', 'RRRR-MM-DD'),'Y');
--행 60
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목60','내용60',2,0,to_date('2024-03-01', 'RRRR-MM-DD'),'Y');
--행 61
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목61','내용61',1,0,to_date('2024-03-02', 'RRRR-MM-DD'),'Y');
--행 62
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목62','내용62',2,0,to_date('2024-03-03', 'RRRR-MM-DD'),'Y');
--행 63
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목63','내용63',1,0,to_date('2024-03-04', 'RRRR-MM-DD'),'Y');
--행 64
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목64','내용64',2,0,to_date('2024-03-05', 'RRRR-MM-DD'),'Y');
--행 65
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목65','내용65',1,0,to_date('2024-03-06', 'RRRR-MM-DD'),'Y');
--행 66
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목66','내용66',2,0,to_date('2024-03-07', 'RRRR-MM-DD'),'Y');
--행 67
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목67','내용67',1,0,to_date('2024-03-08', 'RRRR-MM-DD'),'Y');
--행 68
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목68','내용68',2,0,to_date('2024-03-09', 'RRRR-MM-DD'),'Y');
--행 69
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목69','내용69',1,0,to_date('2024-03-10', 'RRRR-MM-DD'),'Y');
--행 70
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목70','내용70',2,0,to_date('2024-03-11', 'RRRR-MM-DD'),'Y');
--행 71
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목71','내용71',1,0,to_date('2024-03-12', 'RRRR-MM-DD'),'Y');
--행 72
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목72','내용72',2,0,to_date('2024-03-13', 'RRRR-MM-DD'),'Y');
--행 73
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목73','내용73',1,0,to_date('2024-03-14', 'RRRR-MM-DD'),'Y');
--행 74
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목74','내용74',2,0,to_date('2024-03-15', 'RRRR-MM-DD'),'Y');
--행 75
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목75','내용75',1,0,to_date('2024-03-16', 'RRRR-MM-DD'),'Y');
--행 76
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목76','내용76',2,0,to_date('2024-03-17', 'RRRR-MM-DD'),'Y');
--행 77
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목77','내용77',1,0,to_date('2024-03-18', 'RRRR-MM-DD'),'Y');
--행 78
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목78','내용78',2,0,to_date('2024-03-19', 'RRRR-MM-DD'),'Y');
--행 79
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목79','내용79',1,0,to_date('2024-03-20', 'RRRR-MM-DD'),'Y');
--행 80
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목80','내용80',2,0,to_date('2024-03-21', 'RRRR-MM-DD'),'Y');
--행 81
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목81','내용81',1,0,to_date('2024-03-22', 'RRRR-MM-DD'),'Y');
--행 82
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목82','내용82',2,0,to_date('2024-03-23', 'RRRR-MM-DD'),'Y');
--행 83
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목83','내용83',1,0,to_date('2024-03-24', 'RRRR-MM-DD'),'Y');
--행 84
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목84','내용84',2,0,to_date('2024-03-25', 'RRRR-MM-DD'),'Y');
--행 85
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목85','내용85',1,0,to_date('2024-03-26', 'RRRR-MM-DD'),'Y');
--행 86
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목86','내용86',2,0,to_date('2024-03-27', 'RRRR-MM-DD'),'Y');
--행 87
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목87','내용87',1,0,to_date('2024-03-28', 'RRRR-MM-DD'),'Y');
--행 88
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목88','내용88',2,0,to_date('2024-03-29', 'RRRR-MM-DD'),'Y');
--행 89
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목89','내용89',1,0,to_date('2024-03-30', 'RRRR-MM-DD'),'Y');
--행 90
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목90','내용90',2,0,to_date('2024-03-31', 'RRRR-MM-DD'),'Y');
--행 91
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목91','내용91',1,0,to_date('2024-04-01', 'RRRR-MM-DD'),'Y');
--행 92
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목92','내용92',2,0,to_date('2024-04-02', 'RRRR-MM-DD'),'Y');
--행 93
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목93','내용93',1,0,to_date('2024-04-03', 'RRRR-MM-DD'),'Y');
--행 94
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목94','내용94',2,0,to_date('2024-04-04', 'RRRR-MM-DD'),'Y');
--행 95
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목95','내용95',1,0,to_date('2024-04-05', 'RRRR-MM-DD'),'Y');
--행 96
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목96','내용96',2,0,to_date('2024-04-06', 'RRRR-MM-DD'),'Y');
--행 97
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목97','내용97',1,0,to_date('2024-04-07', 'RRRR-MM-DD'),'Y');
--행 98
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목98','내용98',2,0,to_date('2024-04-08', 'RRRR-MM-DD'),'Y');
--행 99
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목99','내용99',1,0,to_date('2024-04-09', 'RRRR-MM-DD'),'Y');
--행 100
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목100','내용100',2,0,to_date('2024-04-10', 'RRRR-MM-DD'),'Y');
--행 101
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목101','내용101',1,0,to_date('2024-04-11', 'RRRR-MM-DD'),'Y');
--행 102
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목102','내용102',2,0,to_date('2024-04-12', 'RRRR-MM-DD'),'Y');
--행 103
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목103','내용103',1,0,to_date('2024-04-13', 'RRRR-MM-DD'),'Y');
--행 104
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,40,'제목104','내용104',2,0,to_date('2024-04-14', 'RRRR-MM-DD'),'Y');
--행 105
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,10,'제목105','내용105',1,0,to_date('2024-04-15', 'RRRR-MM-DD'),'Y');
--행 106
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,20,'제목106','내용106',2,0,to_date('2024-04-16', 'RRRR-MM-DD'),'Y');
--행 107
INSERT INTO BOARD (BOARD_NO, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BNO.NEXTVAL,30,'제목107','내용107',1,0,to_date('2024-04-17', 'RRRR-MM-DD'),'Y');
